/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedNotificationsRouteImport } from './routes/_authenticated.notifications'
import { Route as AuthenticatedGithubRouteImport } from './routes/_authenticated.github'
import { Route as AuthenticatedDepsRouteImport } from './routes/_authenticated.deps'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated.dashboard'
import { Route as AuthenticatedAnalyticsRouteImport } from './routes/_authenticated.analytics'
import { Route as AuthenticatedTeamsIndexRouteImport } from './routes/_authenticated.teams.index'
import { Route as AuthenticatedTeamsIdRouteImport } from './routes/_authenticated.teams.$id'
import { Route as AuthenticatedScanNewRouteImport } from './routes/_authenticated.scan.new'
import { Route as AuthenticatedScanIdRouteImport } from './routes/_authenticated.scan.$id'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedNotificationsRoute =
  AuthenticatedNotificationsRouteImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedGithubRoute = AuthenticatedGithubRouteImport.update({
  id: '/github',
  path: '/github',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDepsRoute = AuthenticatedDepsRouteImport.update({
  id: '/deps',
  path: '/deps',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAnalyticsRoute = AuthenticatedAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedTeamsIndexRoute = AuthenticatedTeamsIndexRouteImport.update({
  id: '/teams/',
  path: '/teams/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedTeamsIdRoute = AuthenticatedTeamsIdRouteImport.update({
  id: '/teams/$id',
  path: '/teams/$id',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedScanNewRoute = AuthenticatedScanNewRouteImport.update({
  id: '/scan/new',
  path: '/scan/new',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedScanIdRoute = AuthenticatedScanIdRouteImport.update({
  id: '/scan/$id',
  path: '/scan/$id',
  getParentRoute: () => AuthenticatedRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/analytics': typeof AuthenticatedAnalyticsRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/deps': typeof AuthenticatedDepsRoute
  '/github': typeof AuthenticatedGithubRoute
  '/notifications': typeof AuthenticatedNotificationsRoute
  '/scan/$id': typeof AuthenticatedScanIdRoute
  '/scan/new': typeof AuthenticatedScanNewRoute
  '/teams/$id': typeof AuthenticatedTeamsIdRoute
  '/teams/': typeof AuthenticatedTeamsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/analytics': typeof AuthenticatedAnalyticsRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/deps': typeof AuthenticatedDepsRoute
  '/github': typeof AuthenticatedGithubRoute
  '/notifications': typeof AuthenticatedNotificationsRoute
  '/scan/$id': typeof AuthenticatedScanIdRoute
  '/scan/new': typeof AuthenticatedScanNewRoute
  '/teams/$id': typeof AuthenticatedTeamsIdRoute
  '/teams': typeof AuthenticatedTeamsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/auth': typeof AuthRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/_authenticated/analytics': typeof AuthenticatedAnalyticsRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/deps': typeof AuthenticatedDepsRoute
  '/_authenticated/github': typeof AuthenticatedGithubRoute
  '/_authenticated/notifications': typeof AuthenticatedNotificationsRoute
  '/_authenticated/scan/$id': typeof AuthenticatedScanIdRoute
  '/_authenticated/scan/new': typeof AuthenticatedScanNewRoute
  '/_authenticated/teams/$id': typeof AuthenticatedTeamsIdRoute
  '/_authenticated/teams/': typeof AuthenticatedTeamsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/sitemap.xml'
    | '/analytics'
    | '/dashboard'
    | '/deps'
    | '/github'
    | '/notifications'
    | '/scan/$id'
    | '/scan/new'
    | '/teams/$id'
    | '/teams/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/sitemap.xml'
    | '/analytics'
    | '/dashboard'
    | '/deps'
    | '/github'
    | '/notifications'
    | '/scan/$id'
    | '/scan/new'
    | '/teams/$id'
    | '/teams'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/sitemap.xml'
    | '/_authenticated/analytics'
    | '/_authenticated/dashboard'
    | '/_authenticated/deps'
    | '/_authenticated/github'
    | '/_authenticated/notifications'
    | '/_authenticated/scan/$id'
    | '/_authenticated/scan/new'
    | '/_authenticated/teams/$id'
    | '/_authenticated/teams/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  AuthRoute: typeof AuthRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/notifications': {
      id: '/_authenticated/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof AuthenticatedNotificationsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/github': {
      id: '/_authenticated/github'
      path: '/github'
      fullPath: '/github'
      preLoaderRoute: typeof AuthenticatedGithubRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/deps': {
      id: '/_authenticated/deps'
      path: '/deps'
      fullPath: '/deps'
      preLoaderRoute: typeof AuthenticatedDepsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/analytics': {
      id: '/_authenticated/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AuthenticatedAnalyticsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/teams/': {
      id: '/_authenticated/teams/'
      path: '/teams'
      fullPath: '/teams/'
      preLoaderRoute: typeof AuthenticatedTeamsIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/teams/$id': {
      id: '/_authenticated/teams/$id'
      path: '/teams/$id'
      fullPath: '/teams/$id'
      preLoaderRoute: typeof AuthenticatedTeamsIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/scan/new': {
      id: '/_authenticated/scan/new'
      path: '/scan/new'
      fullPath: '/scan/new'
      preLoaderRoute: typeof AuthenticatedScanNewRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/scan/$id': {
      id: '/_authenticated/scan/$id'
      path: '/scan/$id'
      fullPath: '/scan/$id'
      preLoaderRoute: typeof AuthenticatedScanIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedAnalyticsRoute: typeof AuthenticatedAnalyticsRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedDepsRoute: typeof AuthenticatedDepsRoute
  AuthenticatedGithubRoute: typeof AuthenticatedGithubRoute
  AuthenticatedNotificationsRoute: typeof AuthenticatedNotificationsRoute
  AuthenticatedScanIdRoute: typeof AuthenticatedScanIdRoute
  AuthenticatedScanNewRoute: typeof AuthenticatedScanNewRoute
  AuthenticatedTeamsIdRoute: typeof AuthenticatedTeamsIdRoute
  AuthenticatedTeamsIndexRoute: typeof AuthenticatedTeamsIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAnalyticsRoute: AuthenticatedAnalyticsRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedDepsRoute: AuthenticatedDepsRoute,
  AuthenticatedGithubRoute: AuthenticatedGithubRoute,
  AuthenticatedNotificationsRoute: AuthenticatedNotificationsRoute,
  AuthenticatedScanIdRoute: AuthenticatedScanIdRoute,
  AuthenticatedScanNewRoute: AuthenticatedScanNewRoute,
  AuthenticatedTeamsIdRoute: AuthenticatedTeamsIdRoute,
  AuthenticatedTeamsIndexRoute: AuthenticatedTeamsIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  AuthRoute: AuthRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
